[tool.poetry]
name = "lab1"
version = "0.1.0"
description = ""
authors = ["Luigi Federico <luigi.fede.22@gmail.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.10"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
